spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1qaz
  resources:
    static-locations: classpath:/static
#  mvc:
#    static-path-pattern: /static/**    #不然无法访问css,js等文件
#
#    view:
#      prefix: /user/
#      suffix: .jsp





